image: gitlab/dind

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

polymer2:
  stage: build
  script:
    - docker build -t Polymer2:$CI_COMMIT_SHA ./polymer2/
    - docker push Polymer2:$CI_COMMIT_SHA