image: gitlab/dind

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

polymer2:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ./polymer2/
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
