image: gitlab/dind

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

polymer2:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/polymer2 -t $CI_REGISTRY_IMAGE/polymer2:$CI_JOB_ID ./polymer2/
    - docker push $CI_REGISTRY_IMAGE/polymer2:$CI_JOB_ID
    - docker push $CI_REGISTRY_IMAGE/polymer2:latest
